apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vc-scheduler
spec:
  selector:
    matchLabels:
      app: vchamber
      tier: scheduler
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: vchamber
        tier: scheduler
    spec:
      containers:
      - name: scheduler
        image: iad.ocir.io/ssz/vchamber/scheduler:v1
        ports:
        - containerPort: 8080 #Endpoint port
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  type: LoadBalancer #Exposes the service as a node port
  ports:
  - name: restful
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: vchamber
    tier: scheduler