apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vc-frontend
spec:
  selector:
    matchLabels:
      app: vchamber
      tier: frontend
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: vchamber
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: iad.ocir.io/ssz/vchamber/frontend:v1
        ports:
        - containerPort: 80 #Endpoint port
        - containerPort: 443
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer #Exposes the service as a node port
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vchamber
    tier: frontend